// pabrik-api.ts -- klien API workspace PABRIK B2-B7 (backend /ops/*). PABRIK_FE_B2B7_9SEP2026.
import { request } from "./api";

export type Saldo = { sak_kosong: number; sak_rusak_belum_retur: number; stok_jadi: number; kas: number };
export type Lot = { lot_id: number; nomor_lot: string; petak_id: number; petak: string; status: string; tanggal_buka: string; tanggal_tutup: string | null; kubik_masuk: number; sak_jadi: number; sak_lolos_qc: number; rendemen: number | null; sisa_wip_estimasi_kubik: number | null; umur_hari: number; lewat_batas_karung: boolean };
export type Tahap = { id: number; tahap: string; tanggal_mulai: string; ec: number | null; kadar_air_pct: number | null; catatan: string | null };
export type Penerimaan = { id: number; no_urut: number; tahun: number; tanggal: string; jam: string; nopol: string; pemasok_id: number; pemasok: string; p_m: number; l_m: number; t_m: number; kubik_masuk: number; lot_id: number; nomor_lot: string; catatan: string | null; dibatalkan: boolean };
export type Sak = { id: number; tanggal: string; jenis: string; delta: number; jumlah: number; pemasok_id: number | null; harga_per_sak: number | null; foto_nota: string | null; ref_produksi_id: number | null; ref_kas_id: number | null; keterangan: string | null; dibatalkan: boolean };
export type Produksi = { id: number; tanggal: string; lot_id: number; nomor_lot: string; jumlah_sak: number; berat_sampel: number[] | null; status_qc: string; catatan: string | null; dibatalkan: boolean };
export type Kas = { id: number; tanggal: string; jenis: string; kategori: string; nominal: number; keterangan: string | null; foto_nota: string | null; ref_sak_mutasi_id: number | null; created_by: number; dibatalkan: boolean };
export type Upah = { id: number; tanggal: string; nama: string; peran: string; satuan: string; jumlah: number; tarif: number; total: number; kas_id: number; catatan: string | null; dibatalkan: boolean };
export type Hpp = { bulan: string; biaya_kas: number; sak_lolos_qc: number; biaya_tanpa_nota: number; hpp_per_sak: number | null };
export type Cuaca = { tanggal: string; sumber: string; hujan_mm: number | null; suhu_max_c: number | null; cuaca_teks: string | null; catatan: string | null };
export type Pengiriman = { id: number; tanggal: string; no_surat_jalan: string; jumlah_sak: number; nopol: string | null; tujuan_kode: string; bap_tertaut: boolean; no_bap: string | null; catatan: string | null; dibatalkan: boolean };
export type BapPilihan = { bap_id: number; no_bap: string; tgl_bap: string; qty: number; satuan: string; badan_usaha: string; sudah_tertaut?: boolean };
export type BapPabrik = { pengiriman_id: number; no_surat_jalan: string; tanggal_kirim: string; jumlah_sak: number; tujuan_kode: string; no_bap: string; tgl_bap: string; qty_bap: number; satuan_bap: string; sak_klaim: number };
export type Klaim = { id: number; tanggal_terima: string; pengiriman_id: number; no_surat_jalan: string; jumlah_sak_diklaim: number; jenis: string; potongan_sak: number; keterangan: string | null; dibatalkan: boolean };
export type Potongan = { id: number; bulan: string; sebab: string; sak: number; ref_tabel: string | null; ref_id: number | null; keterangan: string | null; dibatalkan: boolean };
export type Rekap = { id: number; bulan: string; karyawan_id: number; sak_bap: number; m3_kks_tanpa_konversi: number; sak_dikirim: number; potongan: number; sak_netto: number; sisa_negatif: number; bonus_jenjang: number; sak_klaim: number; pct_klaim: number; pengali: number; bonus_bulan: number; status: string; rincian?: Record<string, unknown> };
export type Triwulan = { periode: string; karyawan_id: number; bulan: { bulan: string; bonus: number; status: string }[]; semua_dibekukan: boolean; total_dibekukan: number; dibayar: { id: number; total: number; tanggal: string } | null };
export type Karyawan = { id: number; nama: string; peran: string; gaji_pokok: number; uang_makan: number; user_id: number | null; berlaku_mulai: string; berlaku_sampai: string | null; catatan: string | null };
export type Opname = { id: number; tanggal: string; jenis: string; objek_id: number | null; objek: string | null; nilai_terukur: number; nilai_sistem: number; selisih: number; ref_mutasi_id: number | null; berita_acara_foto: string | null; disaksikan_oleh: string | null; catatan: string | null; created_by: number; dibatalkan: boolean };
export type TutupHari = { id: number; tanggal: string; ringkasan: Record<string, unknown>; catatan: string | null; created_by: number; created_at: string; dibatalkan: boolean };
export type Temuan = { id: number; kode: string; nama_cek: string; tingkat: string; ref_tabel: string | null; ref_id: number | null; pesan: string; detail: Record<string, unknown> | null; usulan_potongan_sak: number | null; status: string; tanggal_audit: string; terakhir_dilihat: string; penjelasan: string | null; penjelasan_oleh: number | null; ditutup_oleh: number | null; ditutup_pada: string | null; catatan_tutup: string | null };
export type HasilAudit = { tanggal: string; baru: Temuan[]; selesai_otomatis: { id: number; kode: string; pesan: string }[]; terbuka: Temuan[]; laporan: string; telegram_terkirim: boolean | null };

const q = (p: Record<string, string | number | boolean | undefined | null>) => {
  const s = Object.entries(p).filter(([, v]) => v !== undefined && v !== null && v !== "").map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
  return s ? `?${s}` : "";
};
const post = <T,>(path: string, body?: unknown) => request<T>(path, { method: "POST", body: body === undefined ? undefined : JSON.stringify(body) });
export const batal = (path: string, id: number, alasan: string) => post<unknown>(`${path}/${id}/batal`, { alasan });

export const getSaldo = () => request<Saldo>("/ops/saldo");
export const listLot = (hanyaAktif = false) => request<Lot[]>(`/ops/lot${q({ hanya_aktif: hanyaAktif || undefined })}`);
export const bukaLot = (b: { petak_id: number; tanggal_buka: string }) => post<Lot>("/ops/lot", b);
export const listTahap = (lotId: number) => request<Tahap[]>(`/ops/lot/${lotId}/tahap`);
export const ubahTahap = (lotId: number, b: { tahap: string; tanggal_mulai: string; ec?: number; kadar_air_pct?: number; catatan?: string }) => post<Lot>(`/ops/lot/${lotId}/tahap`, b);
export const listPenerimaan = (bulan?: string, lotId?: number) => request<Penerimaan[]>(`/ops/penerimaan${q({ bulan, lot_id: lotId })}`);
export const terimaTruk = (b: { tanggal: string; jam: string; nopol: string; pemasok_id: number; p_m: number; l_m: number; t_m: number; lot_id: number; catatan?: string }) => post<Penerimaan>("/ops/penerimaan", b);
export const listSak = (bulan?: string) => request<Sak[]>(`/ops/sak${q({ bulan })}`);
export const mutasiSak = (b: { tanggal: string; jenis: string; jumlah: number; pemasok_id?: number; harga_per_sak?: number; foto_nota?: string; keterangan?: string }) => post<Sak>("/ops/sak", b);
export const listProduksi = (bulan?: string) => request<Produksi[]>(`/ops/produksi${q({ bulan })}`);
export const produksiBaru = (b: { tanggal: string; lot_id: number; jumlah_sak: number; berat_sampel?: number[]; catatan?: string }) => post<Produksi>("/ops/produksi", b);
export const listKas = (bulan?: string) => request<Kas[]>(`/ops/kas${q({ bulan })}`);
export const kasBaru = (b: { tanggal: string; jenis: string; kategori?: string; nominal: number; keterangan?: string; foto_nota?: string }) => post<Kas>("/ops/kas", b);
export const listUpah = (bulan?: string) => request<Upah[]>(`/ops/upah${q({ bulan })}`);
export const upahBaru = (b: { tanggal: string; nama: string; peran: string; satuan: string; jumlah: number; tarif?: number; catatan?: string }) => post<Upah>("/ops/upah", b);
export const listHpp = () => request<Hpp[]>("/ops/hpp");
export const listCuaca = (hari = 14) => request<Cuaca[]>(`/ops/cuaca${q({ hari })}`);
export const cuacaManual = (b: { tanggal: string; hujan_mm?: number; cuaca_teks?: string; catatan?: string }) => post<unknown>("/ops/cuaca", b);
export const listPengiriman = (bulan?: string) => request<Pengiriman[]>(`/ops/pengiriman${q({ bulan })}`);
export const pengirimanBaru = (b: { tanggal: string; no_surat_jalan: string; jumlah_sak: number; nopol?: string; tujuan_kode: string; catatan?: string }) => post<Pengiriman>("/ops/pengiriman", b);
export const bapPilihan = (bulan?: string) => request<BapPilihan[]>(`/ops/bap-pilihan${q({ bulan })}`);
export const tautkanBap = (id: number, bapId: number) => post<Pengiriman>(`/ops/pengiriman/${id}/tautkan-bap`, { bap_id: bapId });
export const lepasBap = (id: number) => post<Pengiriman>(`/ops/pengiriman/${id}/lepas-bap`);
export const listBapPabrik = (bulan?: string) => request<BapPabrik[]>(`/ops/bap-pabrik${q({ bulan })}`);
export const listKlaim = (bulan?: string) => request<Klaim[]>(`/ops/klaim${q({ bulan })}`);
export const klaimBaru = (b: { tanggal_terima: string; pengiriman_id: number; jumlah_sak_diklaim: number; jenis: string; bukti?: string; keterangan?: string }) => post<{ id: number; potongan_sak: number; bulan_potongan: string }>("/ops/klaim", b);
export const listPotongan = (bulan?: string) => request<Potongan[]>(`/ops/potongan${q({ bulan })}`);
export const potonganBaru = (b: { bulan: string; sebab: string; sak: number; keterangan: string }) => post<{ id: number }>("/ops/potongan", b);
export const rekapBonus = (bulan: string, karyawanId?: number) => request<Rekap[]>(`/ops/bonus/rekap${q({ bulan, karyawan_id: karyawanId })}`);
export const bekukan = (bulan: string, karyawanId: number) => post<Rekap>(`/ops/bonus/rekap/${bulan}/${karyawanId}/bekukan`);
export const triwulan = (periode: string) => request<Triwulan[]>(`/ops/bonus/triwulan${q({ periode })}`);
export const bayarTriwulan = (b: { periode: string; karyawan_id: number; tanggal_bayar: string; bukti?: string; catatan?: string }) => post<{ id: number; total: number }>("/ops/bonus/triwulan/bayar", b);
export const listKaryawan = () => request<Karyawan[]>("/ops/karyawan");
export const karyawanBaru = (b: { nama: string; peran: string; gaji_pokok?: number; uang_makan?: number; user_id?: number; berlaku_mulai: string; catatan?: string }) => post<Karyawan>("/ops/karyawan", b);
export const listOpname = (jenis?: string) => request<Opname[]>(`/ops/opname${q({ jenis })}`);
export const opnameBaru = (b: { tanggal: string; jenis: string; objek_id?: number; nilai_terukur: number; berita_acara_foto?: string; disaksikan_oleh?: string; catatan?: string }) => post<Opname>("/ops/opname", b);
export const listTutupHari = (hari = 31) => request<TutupHari[]>(`/ops/tutup-hari${q({ hari })}`);
export const ringkasanHari = (tanggal?: string) => request<{ tanggal: string; sudah_ditutup: boolean; tutup_hari_id: number | null; ringkasan: Record<string, unknown> }>(`/ops/tutup-hari/ringkasan${q({ tanggal })}`);
export const tutupHari = (b: { tanggal: string; catatan?: string }) => post<TutupHari>("/ops/tutup-hari", b);
export const listTemuan = (status = "terbuka", kode?: string) => request<Temuan[]>(`/ops/audit${q({ status, kode })}`);
export const jalankanAudit = (kirim = false) => post<HasilAudit>(`/ops/audit/jalankan${q({ kirim })}`);
export const penjelasanTemuan = (id: number, penjelasan: string) => post<Temuan>(`/ops/audit/${id}/penjelasan`, { penjelasan });
export const tutupTemuan = (id: number, catatan: string) => post<Temuan>(`/ops/audit/${id}/tutup`, { catatan });
export const terimaPotongan = (id: number, sak?: number) => post<{ potongan_id: number }>(`/ops/audit/${id}/terima-potongan`, sak ? { sak } : {});
